Repository spring-cloud/spring-cloud-dataflow, pull requests merged in 2019-02, with the labels that each got.

#2822 Resolves missing DSL in task detail request
  spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java
Labels: in pr

#2829 Update documentation config
  spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
Labels: in pr

#2846 Polish dependencies
  pom.xml
  spring-cloud-dataflow-dependencies/pom.xml
  spring-cloud-dataflow-registry/pom.xml
  spring-cloud-dataflow-server-core/pom.xml
Labels: in pr

#2890 gh-2872 Fix security-docs links in the reference guide
  spring-cloud-dataflow-docs/src/main/asciidoc/architecture.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc
Labels: in pr

#2912 Fix docs to run server locally against a remote CF environment
  spring-cloud-dataflow-docs/src/main/asciidoc/appendix-howto.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc
Labels: in pr

#2916 Updated version of image used for docker test
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/validation/DefaultAppValidationServiceTests.java
Labels: in pr

#2913 Added version to CTR maven URL example
  spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc
Labels: in pr

#2919 Remove circuit breaker configuration
  spring-cloud-dataflow-server-core/pom.xml
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
Labels: in pr

#2921 Update to Einstein.GA bit.ly links
  spring-cloud-dataflow-docs/src/main/asciidoc/streams-monitoring-local.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
Labels: documentation 📝, in pr

#2925 gh-2853 Document the configuration of `DataflowTemplate` with OAuth's password-grant credentials
  spring-cloud-dataflow-docs/src/main/asciidoc/appendix-dataflow-template.adoc
Labels: in pr

#2936 Any property suffixed with 'url' will be redacted
  spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java
Labels: in pr

#2948 Remove unused file/single security tests
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityRootWithUsersFileTests.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityRootWithUsersFileTestsWithTasksAndWithoutStreamsMetricsAndSchedules.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityRootWithUsersFileTestsWithoutTasks.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityRootWithUsersFileTestsWithoutTasksAndStreams.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityRootWithUsersFileTestsWithoutTasksAndStreamsAndMetrics.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityWithSingleUserTests.java
  spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityWithUsersFileTestsWithoutTasks.java
  spring-cloud-starter-dataflow-server/src/test/resources/org/springframework/cloud/dataflow/server/single/security/fileBasedUsers.yml
  spring-cloud-starter-dataflow-server/src/test/resources/org/springframework/cloud/dataflow/server/single/security/singleUser.yml
Labels: in pr

#2947 Remove unused BatchTaskIndexesDatabaseInitializer
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/BatchTaskIndexesDatabaseInitializer.java
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
Labels: in pr

#2951 Update readme
  README.adoc
  README.md
Labels: in pr

#2954 Fixed a couple of misspells and 2 bugs in docs.
  spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-local.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-stream-create.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-stream-definition-deploy.png
  spring-cloud-dataflow-docs/src/main/asciidoc/streams-monitoring-local.adoc
Labels: in pr

#2960 Resolves problem with testTaskLaunch
  spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTemplate.java
Labels: bug 🐞, in pr

#2959 Improve documentation
  spring-cloud-dataflow-classic-docs/src/test/resources/org/springframework/restdocs/templates/asciidoctor/path-parameters.snippet
  spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-app-list-batch-event.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-job-execution-details.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-job-execution-list.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-shell-app-list.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-task-execution-list-batch-events.png
  spring-cloud-dataflow-docs/src/main/asciidoc/images/dataflow-task-execution-list-timestamp.png
  spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/task-developer-guide.adoc
  spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc
Labels: documentation 📝, in pr
