Repository spring-cloud/spring-cloud-dataflow, pull requests merged in 2024-11, with the labels that each got.

#6037 Added a negative test to DataflowOAuthIT
  spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/oauth/DataflowOAuthIT.java
Labels: review/all-required

#6064 Replace deprecated asList method with asInstanceOf.
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
Labels: review/at-least-one

#6065 Replace deprecated YamlMapper configure methods to use its builder
  spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/CloudFoundryApplicationManifestReader.java
Labels: review/at-least-one

#6070 Update to Prometheus RSocket Proxy 2.0.0-M2
  spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
  src/carvel/config/values/values.yml
  src/carvel/docs/configuration-options.adoc
  src/deploy/carvel/load-images.sh
  src/deploy/images/pull-prometheus-rsocket-proxy.sh
  src/deploy/k8s/deploy-scdf.sh
  src/docker-compose/docker-compose-prometheus.yml
  src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
  src/templates/docker-compose/docker-compose-prometheus.yml
  src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
Labels: review/at-least-one

#6062 Back port of Task Thin Execution List and List By Name
  spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
  spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
  spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
  spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
  spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
  spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionThinController.java
  spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/TaskDefinitionRepository.java
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
  spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
  spring-cloud-dataflow-server-core/src/test/resources/root-controller-result.json
Labels: type/backport, review/at-least-one

#6073 Disable Trivy by default
  .github/workflows/ci.yml
Labels: review/at-least-one

#6080 Provide for disabling security scan in ci-pr.yml and adding alternative repo
  .github/workflows/ci-pr.yml
  .github/workflows/ci.yml
Labels: review/at-least-one

#6079 Provide for alternative trivy repos
  .github/workflows/ci.yml
Labels: review/at-least-one

#6082 [CI] Update jfrog cli to v3
  .github/workflows/build-snapshot-worker.yml
  .github/workflows/cental-sync.yml
  .github/workflows/central-release.yml
  .github/workflows/ci.yml
  .github/workflows/milestone-worker.yml
  .github/workflows/next-dev-version-worker.yml
  .github/workflows/promote-milestone.yml
  .github/workflows/promote-release.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release-worker.yml
Labels: review/at-least-one
